import { Food } from './app/shared/models/Food';

export const sample_foods: Food[] = [
  {
    id: '1',
    name: 'Піца Пепероні',
    cookTime: '10-20',
    price: 139,
    favorite: false,
    origins: ['Італія'],
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'М`ясні кульки',
    price: 175.40,
    cookTime: '20-30',
    favorite: true,
    origins: [ 'Середній Схід', 'Китай'],
    imageUrl: 'assets/food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'Гамбургер',
    price: 55.90,
    cookTime: '10-15',
    favorite: false,
    origins: ['Німеччина', 'США'],
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '4',
    name: 'Смажена картопля',
    price: 35,
    cookTime: '15-20',
    favorite: true,
    origins: ['Бельгія', 'Франція'],
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '5',
    name: 'Курячий суп',
    price: 119,
    cookTime: '40-50',
    favorite: false,
    origins: ['Індія', 'Азія'],
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '6',
    name: 'Вегетаріанська піца',
    price: 250.50,
    cookTime: '40-50',
    favorite: false,
    origins: ['Італія'],
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
];
